name: Auto Comment

on:
  issue_comment:
    types: [created, edited, deleted]
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  auto-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add comment to Issue or PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issueNumber = context.issue.number;
            const repo = context.repo;
            
            let commentBody = "확인 필요";
            
            if (context.eventName === 'issue_comment') {
              commentBody += `\n\nIssue Comment ${context.payload.action} by ${context.payload.comment.user.login}`;
            } else if (context.eventName === 'pull_request') {
              commentBody += `\n\nPull Request ${context.payload.action} by ${context.payload.pull_request.user.login}`;
            }
            
            await github.rest.issues.createComment({
              ...repo,
              issue_number: issueNumber,
              body: commentBody
            });