name: Learn Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
        default: 'GitHub User'
      message:
        description: 'Message to display'
        required: true
        default: 'Hello, World!'
      environment:
        description: 'Environment to run script'
        type: choice
        required: true
        default: 'development'
        options:
        - development
        - staging
        - production

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Greet the user
      run: |
        echo "Hello, ${{ github.event.inputs.name }}!"
        echo "Your message: ${{ github.event.inputs.message }}"
        echo "Running in ${{ github.event.inputs.environment }} environment"
    
  example-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: echo "This is an example job triggered by workflow_dispatch"
    - name: Run a multi-line script
      run: |
        echo "Add other actions to build,"
        echo "test, and deploy your project."
        echo "Environment: ${{ github.event.inputs.environment }}"
    - name: Send slack when failed
      # 실패했을 때 실행되겠죠?
      if: ${{ failure() }}
      # 직접 '만든' Action이므로 uses 키워드를 이용해서 아래 경로를 입력해줍니다.
      uses: ./.github/actions/slack-notify
      # 아까 secrets로 접근할 수 있게 만들어놓은 슬랙 url을 여기에 써볼게요.
      # with 키워드와 함께 slack_incoming_url 값으로 넘겨줍니다.
      with:
        slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}

    - name: Send slack if completed
      # 성공할 때만 실행되겠죠?
      if: ${{ success() }}
      uses: ./.github/actions/slack-notify
      # status input은 받는 쪽에서 default 값을 정해놨기 때문에 success일 때만 넘겨줄게요.
      with:
        status: success
        slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
